port: 8081
watch:
  threshold: 10 # Minute
  wait: 5 # Second
webhook:
  url: "xxx"
  token: "xxx"
  to: "xxx@gmail.com" # 收件人
  title: "xxx" # 通知标题
db:
  host: "ip"
  port: 3306
  user: "xxx"
  pass: "xxx"
  dbname: "xxx"