port: 8081
watch:
  threshold: 5 # Minute 触发告警时间
  wait: 5 # Second 扫描间隔
  repeatInterval: 3 # Minute 告警间隔
webhook:
  url: "xxx"
  token: "xxx"
  to: "xxx@gmail.com" # 收件人
  title: "xxx" # 通知标题
db:
  host: "ip"
  port: 3306
  user: "xxx"
  pass: "xxx"
  dbname: "xxx"